name: Github Snake

on:
  push:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: "0 */24 * * *"

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-snake.svg?color_snake=orange
            assets/github-snake-dark.svg?palette=github-dark&color_snake=orange

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output/github-snake
          build_dir: assets
          commit_message: "build: generate github snake"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}